### PR TITLE
Allow to create a file when filesystem don't support hard links

### PR DESCRIPTION
**Pull request by piranna**
This fix issue #43

### CODE REVIEW

**Comment by mafintosh** [comment]
ah you are way ahead of me. looks good. this option name is a bit too descriptive for my normal taste but lgtm

**Comment by piranna** [comment]
Any suggestion for the option name? Also I would like to do some checks,
don't merge yet.

**Comment by piranna** [comment]
I have just done the checks and now it can be safely merged, just suggest
me a better name for the option and we are ready :-)

**Comment by piranna** [comment]
Any update on this? I would like to integrate this change on `prebuild-install`... Any suggestion for a better name for the option?

**Comment by mafintosh** [comment]
Sorry I was in an airplane when you wrote so missed it. I'd call it `hardlinkAsFilesFallback`

**Comment by piranna** [comment]
> Sorry I was in an airplane when you wrote so missed it.

Don't worry :-)


> I'd call it hardlinkAsFilesFallback

Ok, I'll change it and update the pull-request.

**Comment by piranna** [comment]
Done :-)

**Comment by piranna** [comment]
Thank you! ^^

**Pull request merged**
