### PR TITLE
chore!: migrate from mkdirp to fs.mkdir

### PR DESCRIPTION
**Pull request by childish-sambino**
Fixes https://github.com/mafintosh/tar-fs/issues/84

### CODE REVIEW

**Comment by mafintosh** [comment]
Can you change this to use fs.mkdir(..., { recursive: true }) ?

**Comment by childish-sambino** [comment]
Looks like the recursive option was added in Node 10.12 but I have clients that still run Node 8 (I know, recently deprecated). I'm okay with dropping Node 6 though.

**Comment by mafintosh** [comment]
Oh annoying. I use mkdirp so many places, so I think I’m just gonna mirror the old source from that into a package cause it worked perfectly fine.

**Comment by fraxken** [comment]
That's why this is a semver major update.

Node.js 8 is EOL since at least six months. We have to move forward to avoid keeping a legacy code base.

**Comment by childish-sambino** [comment]
@fraxken Node.js was EOL in 2019-12-31 (< 4 months ago), but I still understand your concern. I'm checking usage for my app to see how much Node 8 activity there is.

**Comment by childish-sambino** [comment]
Updated to migrate from mkdirp to fs.mkdir

**Comment by mafintosh** [comment]
Down to move to fs.mkdirp next time we do a new major bump.

For now I moved it to use mkdirp-classic with is a mirror I just made of the existing working code.

**Comment by mafintosh** [comment]
(will upgrade to recursive mkdir when we bump major, closing for now, thanks!)

**Pull request closed without merging**
