### PR TITLE
Added `umask` option for `pack()` function

### LINKED ISSUE #56: `umask` option for pack
Add `umask` option for packing in addition to `dmode` and `fmode` similar to the one for extract, so files can be stored with their permissions filtered without needed to do `chmod -R` before.

### PR DESCRIPTION
**Pull request by piranna**
This fixes #56

### CODE REVIEW

**Comment by piranna** [comment]
Any update on this? I have tested it for a while and it's working flawlessly so far, so it could be merged and published... :-)

**Comment by piranna** [comment]
Any update on this? I'm trying to clean-up the forks and pull-requests I have done for NodeOS before launching version 1.0.0-RC3 and this is one of them... As I've said before, this is working flawlessly after doing several builds each day :-)

**Comment by mafintosh** [comment]
Sorry for being slow

**Comment by mafintosh** [comment]
1.15.0

**Comment by piranna** [comment]
Thank you and don't worry, we all have a life in the real world :-)

**Pull request merged**
